### PR TITLE
Improvements for MariaDB on Debian Stretch

### PR DESCRIPTION
**Pull request by jaspernbrouwer**
I've changed, hopefully for the best, some things in order to get MariaDB running on Debian Stretch.

This is a redo of #17.

### CODE REVIEW

**Comment by HanXHX** [comment]
Notes on your commit 5fd2e46: you must check `mysql_vendor` = mariadbgalera too.

Your commits add some problems (see: https://travis-ci.org/HanXHX/ansible-mysql/jobs/248102784). Other problems (41.8, 41.9) seems to be Debian or python (lib mysqlclient) related. I'm working on it.

Thank you!

**Comment by HanXHX** [comment]
Please pull my master branch (see #19) before reapply commits.

**Comment by jaspernbrouwer** [comment]
I've rebased this PR on top of your latest, and addressed your note:

> Notes on your commit 5fd2e46: you must check mysql_vendor = mariadbgalera too.

I'll have a look at any build issues as well!

**Comment by HanXHX** [comment]
Based on travis, `jessie-default-mysql-master` is still down... :(

**Comment by jaspernbrouwer** [comment]
MySQL 5.5 (the version on Jessie) uses 5M as `innodb_log_file_size` by default. And because when MySQL is installed, it's also started, the log files are created, and they are 5M.

Next the roles writes the configuration files, `innodb_log_file_size` is set to 64M, MySQL is restarted, and we hit an error.

I've changed the default for `innodb_log_file_size` for MySQL on Jessie, see d74393a.

The tests should pass now!

**Comment by HanXHX** [comment]
Good job!

**Pull request merged**
